### ISSUE TITLE
Can't install due to openssl 0.9

### ISSUE THREAD

**Issue by chevalier-m** [vertexclique/korq#1]
Hello,

I can't install `korq` right now as the open-ssl dependency won't compile:
```
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/tmp/cargo-install5S75FM/release/build/openssl-a3d130bd8be9cd18/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version'
```

A similar issue has been referenced here: https://github.com/sfackler/rust-openssl/issues/987
The fix is to update the openssl dependency to 0.10.

I don't know about Rust at all that's why I won't PR, but it seems a rather easy fix.

Thanks, the project looks good!

EDIT: This is _very likely_ to be realted to my Ubutunu isntall (18.10), which includes OpenSSL 1.1.1, if you wanna reproduce.

**Comment by vertexclique** [comment]
Just released a new version that might possibly fix this.
You can also download it from CI builds under the release tags or you can use:
``` cargo install korq --force```

**Comment by vertexclique** [comment]
Closing… Hope everything works as expected. Thanks!

**Comment by chevalier-m** [comment]
I confirm the fix is successful.
Thanks !
